version: '3.9'

services:
  bookmarks:
    build: .
    restart: always
    command: gunicorn -b 0.0.0.0:8000 bookmarks.wsgi
    volumes:
      - .:/bookmarks
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - "SECRET_KEY=django-insecure-o1-6n8#kmz$$!2++(!=pm!+r%^@x7-or10c1k_f+-#j%o+v(h&("
