version: '3.9'

services:
  bookmarks:
    build: .
    restart: always
    command: python /bookmarks/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookmarks
    ports:
      - 8000:8000
    environment:
      - DEBUG=False
      - SECRET_KEY="sahjashdkjasdnasbndasmdbam34732847328947#@%#$$^$$&^%*&FSSDFW$$@#$$@#$$ERFSDFSDFST$$34##"
      - ALLOWED_HOSTS="render.com"