name: Bookmarks CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-docker-compose:
    runs-on: ubuntu-latest
    steps: 
      - name: check docker-compose is installed
        run: docker-compose --version

  docker-build:
    runs-on: ubuntu-latest
    needs: check-docker-compose
    steps:
    - name: check code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yaml" up -d --build
  
  test:
    runs-on: ubuntu-latest
    needs: [check-docker-compose, docker-build]
    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: run django tests
        run: docker-compose exec bookmarks python manage.py test      

  docker-compose-shutdown:
    runs-on: ubuntu-latest
    needs: [check-docker-compose, docker-build]
    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: shutdown docker-compose
        if: always()
        run: docker-compose down