name: Bookmarks CI workflow

on:
  push:
    branches: [ "main", "deployment"]
  pull_request:
    branches: [ "main" ]

jobs:

  check-docker-compose:
    runs-on: ubuntu-latest
    steps: 
      - name: check docker-compose is installed
        run: docker-compose --version

  docker-build:
    runs-on: ubuntu-latest
    needs: check-docker-compose
    steps:
    - name: check code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yaml" up -d --build
    
    - name: docker logs
      run: docker-compose logs
  
  test:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: check code
        uses: actions/checkout@v3
      
      - name: run django tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pip install pipenv
          pipenv install --system
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
          
      
  docker-compose-shutdown:
    runs-on: ubuntu-latest
    needs: [check-docker-compose, docker-build]
    steps:
      - name: check code
        uses: actions/checkout@v3

      - name: shutdown docker-compose
        if: always()
        run: docker-compose down